// export const NEXT_LYRIC = 'NEXT_LYRIC';
// export const RESTART_SONG = 'RESTART_SONG';
// export const CHANGE_SONG = 'CHANGE_SONG';
export const REQUEST_CHARACTERS = 'REQUEST_CHARACTERS';
export const RECEIVE_CHARACTERS = 'RECEIVE_CHARACTERS';
